LLM_MAX_RETRIES = 3
LLM_RETRY_BASE_DELAY = 5

GO_TEST_TIMEOUT = 120
GO_BUILD_TIMEOUT = 120
SEARCH_FILE_TIMEOUT = 30

REPAIR_MAX_ATTEMPTS = 3

REVIEW_TIMEOUT_MINUTES = 30
REVIEW_POLL_INTERVAL = 5

DASHBOARD_URL_DEFAULT = "http://localhost:3000"
